// C2 parameter definitions for the reverse_tcp profile.
// Mirrors tcpC2Parameters in builder.go.

use mythic_rabbitmq::{structs::parameter_type, C2Parameter};

pub fn c2_parameters() -> Vec<C2Parameter> {
    vec![
        C2Parameter {
            name: "port".to_string(),
            description: "TCP port to listen on".to_string(),
            default_value: serde_json::json!(4444),
            parameter_type: parameter_type::NUMBER.to_string(),
            required: true,
            verifier_regex: "^[0-9]+$".to_string(),
            randomize: false,
            format_string: String::new(),
            is_crypto_type: false,
            choices: vec![],
            dictionary_choices: vec![],
            ui_position: 0,
        },
        C2Parameter {
            name: "killdate".to_string(),
            description: "Kill Date".to_string(),
            default_value: serde_json::json!(365),
            parameter_type: parameter_type::DATE.to_string(),
            required: false,
            verifier_regex: String::new(),
            randomize: false,
            format_string: String::new(),
            is_crypto_type: false,
            choices: vec![],
            dictionary_choices: vec![],
            ui_position: 0,
        },
        C2Parameter {
            name: "encrypted_exchange_check".to_string(),
            description: "Perform Key Exchange".to_string(),
            default_value: serde_json::json!(false),
            parameter_type: parameter_type::BOOLEAN.to_string(),
            required: false,
            verifier_regex: String::new(),
            randomize: false,
            format_string: String::new(),
            is_crypto_type: false,
            choices: vec![],
            dictionary_choices: vec![],
            ui_position: 0,
        },
        C2Parameter {
            name: "AESPSK".to_string(),
            description: "Encryption Type".to_string(),
            default_value: serde_json::json!("none"),
            parameter_type: parameter_type::CHOOSE_ONE.to_string(),
            required: false,
            verifier_regex: String::new(),
            randomize: false,
            format_string: String::new(),
            is_crypto_type: true,
            choices: vec!["aes256_hmac".to_string(), "none".to_string()],
            dictionary_choices: vec![],
            ui_position: 0,
        },
        C2Parameter {
            name: "callback_interval".to_string(),
            description: "Callback Interval in seconds".to_string(),
            default_value: serde_json::json!(10),
            parameter_type: parameter_type::NUMBER.to_string(),
            required: false,
            verifier_regex: "^[0-9]+$".to_string(),
            randomize: false,
            format_string: String::new(),
            is_crypto_type: false,
            choices: vec![],
            dictionary_choices: vec![],
            ui_position: 0,
        },
    ]
}
